### ISSUE TITLE
IPv4 parser and the empty string as input

### ISSUE THREAD

**Issue by triple-underscore** [whatwg/url#96] opened 2016-02-27 01:51 UTC
https://url.spec.whatwg.org/#concept-ipv4-parser

It is unclear what happen if the empty string is passed to the IPv4 parser as input.
The step 3 makes the "parts" list empty, and the algorithm gets stuck at the step 11.
(Probably, the algorithm should return the same input. )

**Comment by annevk** [comment] 2016-02-27 17:32
This is a duplicate of #79 in a way, but I'll leave it open for now.

There's one question here as I see it:

1. Should other standards be able to directly invoke the IPv4 parser? (Inclined to say no.)

If they cannot, then it's simply a matter of making sure that either IPv4 handles it or the host parser never invokes it with the empty string.

**Comment by annevk** [comment] 2016-12-29 15:04
I have a fix for #79 in #189. Marking this as a duplicate since it appears to be a concrete one after all.

**Closed by annevk** 2016-12-29 15:04 UTC
Labels: parser
