### ISSUE TITLE
Should URLSearchParams stringify be called in URL constructor?

### ISSUE THREAD

**Issue by yutakahirano** [whatwg/url#350] opened 2017-10-30 04:11 UTC
```
const url = new URL('http://www.example.com/a=b,c');
const params = url.searchParams;

assert_equals(url.toString(), 'http://www.example.com/a=b,c');
```

```
const url = new URL('http://www.example.com/');
const params = url.searchParams;

params.append('a', 'b,c')

assert_equals(url.toString(), 'http://www.example.com/a=b%2Cc');
```
I feel this difference a bit inconsistent. Is it intentional?

**Comment by TimothyGu** [comment] 2017-10-30 07:20
Duplicate of https://github.com/whatwg/url/issues/18, most likely.

**Comment by annevk** [comment] 2017-10-30 08:05
Yeah, seems like a duplicate of that issue. Will keep this open for now to make sure we explicitly test this example.

**Comment by yutakahirano** [comment] 2017-10-30 23:33
If the behavior is intended, I would like to write a test.

**Closed** 2017-11-01 06:29 UTC

**Comment by annevk** [comment] 2017-11-01 07:24
Thanks!
