### ISSUE TITLE
Consider adding support for fragment parameters

### ISSUE THREAD

**Issue by bryanmcquade** [whatwg/url#389] opened 2018-05-22 18:19 UTC
Domenic Denicola suggested that I open an issue for this.

Various specs and web applications would benefit from standardizing support for fragment parameters, in addition to the existing support for query parameters.

The URL spec defines support for name-value pairs in the query string, parsed by running the application/x-www-form-urlencoded parser (https://url.spec.whatwg.org/#concept-urlencoded-parser).

In addition to the query string, other specs make use of name-value parameter pairs in the fragment portion of the URL. For example, various mime types make use of name=value pairs in their fragment specifications:

Media fragments, e.g. #track=audio&t=10,20 (https://www.w3.org/TR/media-frags/#media-fragment-syntax)
PDF fragment identifiers, e.g. #page=10&zoom=... (https://tools.ietf.org/html/rfc3778#section-3)
text/plain fragment identifiers, e.g. #line=10,20 (https://tools.ietf.org/html/rfc5147#section-3)
CSV fragment identifiers, e.g. #row=4 (https://tools.ietf.org/html/rfc7111#section-3)

More recently, we are looking at extending support for HTML fragment identifiers in https://github.com/bryanmcquade/scroll-to-css-selector and would like to use parameters in the fragment, e.g. #targetElement=.cssClass.

In addition to these specs, it's not uncommon for web apps to want to encode their own application-specific parameters in the fragment. Searching github for "URLSearchParams hash substr  language:JavaScript" shows a number of code snippets that perform an operation like: var fragmentParams = new URLSearchParams(window.location.search.substr(1));. Standardizing fragment params would make it simpler for these apps to consume their fragment params (perhaps on a hashParams property of the URL API, similar to the existing searchParams property).

Standardizing on an encoding scheme for fragment parameters, similar to the existing support for query parameters, would allow other specs that depend on fragment params (those linked above) to reference the standard, rather than having to spec out how to encode these fragments in each individual spec.

In addition, a common encoding scheme with named parameters makes it straightforward to "share" the fragment, encoding both mime-type specific fragment identifiers, as well as application-specific fragment parameters, in a single fragment. For example: #targetElement=.cssClass&myApplicationParam=foo allows for encoding both the targetElement fragment identifier param proposed in https://github.com/bryanmcquade/scroll-to-css-selector as well as any application-specific parameters (in this case myApplicationParam=foo).

**Comment by bryanmcquade** [comment] 2018-05-22 18:21
Some additional notes from Domenic:

* Our first ask is to just put the right concepts in place in the URL Standard: basically, parsing fragments into a list of key/value pairs, instead of just treating them as an opaque string. Then, other specs can reference that parsing.

* There exists a spec for this which seems to be pretty general, but is named "Media Fragments", and doesn't integrate with the URL Standard. Can we basically adopt that work and put it on more solid footing, to meet out first ask?

* Second potential ask: should we add a URLHashParams or URLFragmentParams API to URL as well for manipulating these things?

**Comment by annevk** [comment] 2019-03-01 09:09
I thought since you were in contact with Domenic there was not much for me to say, but since I've been prodded: I think that general approach makes sense. Identify the common data model, parser, and serializer. Write those down and ensure (through tests and filing bugs) that implementations align on those for the various existing users. Also patch the existing specifications that make use of this to use this new model, to ensure it works well. (I'm not super familiar with Media Fragments, but I think you could use it as a starting point, yes.)

Once that's more mature, potentially add an API.

**Comment by annevk** [comment] 2020-05-05 08:20
Is this a duplicate of #445 now? How do these relate?

**Comment by bokand** [comment] 2020-05-15 19:33
Given that we took a different approach than the one mentioned by @bryanmcquade above, this isn't something that'd still be helpful specifically to the text-fragment project.

This looks more broadly useful and might be worth considering but I suspect that without any motivating use case this won't get much action so I think we can probably close it unless someone objects?

**Closed** 2021-02-11 12:52 UTC
Labels: addition/proposal, needs implementer interest
