### ISSUE TITLE
easy initialization: `new URLSearchParams({ using: "a nice API" })`

### ISSUE THREAD

**Issue by timruffles** [whatwg/url#141] opened 2016-08-12 13:41 UTC
It'd be really convenient if you could initialize a search params with an object. It'd cover a lot of use-cases far more concisely than having to imperatively mutate an object post-construction:

```javascript
new URLSearchParams({
  some: dynamicValue,
  [aDynamicKey]: dynamicValue,
});
```

Equally it'd be nice if this worked with a `Map`, or iterators that produce `[k,v]` tuples.

**Comment by annevk** [comment] 2016-08-12 13:46
Yeah makes sense. I'm basically waiting for https://github.com/whatwg/fetch/issues/164 to be sorted.

**Comment by annevk** [comment] 2016-10-19 11:30
Just noticed that this is a duplicate of #27.

**Closed by annevk** 2016-10-19 11:30 UTC
