### ISSUE TITLE
url-representation

### ISSUE THREAD

**Issue by roddrecX** [whatwg/url#298] opened 2017-04-27 04:31 UTC
https://url.spec.whatwg.org/commit-snapshots/488c459d9e4245a3f6bf087e7dcd2c7e91487ac5/#url-representation

**Comment by roddrecX** [comment] 2017-04-27 04:31
thank you so much..

**Comment by annevk** [comment] 2017-04-27 04:45
Closing this since it's unclear what the problem is.

**Closed by annevk** 2017-04-27 04:45 UTC
