### ISSUE TITLE
Figure out what to do with youtube IDNA issues

### ISSUE THREAD

**Issue by Ms2ger** [whatwg/url#131] opened 2016-07-01 13:16 UTC
See https://github.com/servo/rust-url/pull/208

**Comment by annevk** [comment] 2016-07-04 13:06
Should probably mark this as a duplicate of #53. Hmm.

**Comment by annevk** [comment] 2016-07-04 13:08
Yeah, https://github.com/whatwg/url/issues/53#issuecomment-181528158.

**Closed by annevk** 2016-07-04 13:08 UTC
