### ISSUE TITLE
Encode percent(%)s that are not part of a percent-encoded byte when parsing a URL

### ISSUE THREAD

**Issue by duanyao** [whatwg/url#170] opened 2016-12-08 03:18 UTC
Test case:
```
console.log(new URL('/%n', document.baseURI).pathname); // -> /%n
```
This is surperising to me, because I expect that the URL constructor either fail or return a valid url; however, '/%n' is not a valid url. If you feed '/%n' to `decodeURI()`, it will throw a `URIError`.

The spec just say that a percent that is not a part of a percent-encoded byte is a ["syntax violation"](https://url.spec.whatwg.org/#concept-basic-url-parser), but does not require the parser to throw or to fix the syntax.

I suggest encode percent(%)s that are not part of a percent-encoded byte when parsing a URL, i.e. '/%n' becomes '/%25n' after parsing.

**Comment by annevk** [comment] 2016-12-08 20:35
This is a duplicate of #87. It's a little unclear what we can effectively change here.

**Closed by annevk** 2016-12-08 20:35 UTC
